import { en } from './en';

type DeepPartial<T> = T extends object ? { [P in keyof T]?: DeepPartial<T[P]> } : T;

export const bn: DeepPartial<typeof en> = {
  app: {
    name: 'অফলাইন ফাইন্যান্স',
    loading: 'লোড হচ্ছে...',
    error: 'একটি ত্রুটি ঘটেছে',
    retry: 'পুনরায় চেষ্টা করুন',
    success: 'সফল',
    cancel: 'বাতিল',
    save: 'সংরক্ষণ',
    delete: 'মুছুন',
    edit: 'সম্পাদনা',
    close: 'বন্ধ',
    confirm: 'নিশ্চিত',
    ok: 'ঠিক আছে',
    done: 'সম্পন্ন',
    back: 'পেছনে',
    search: 'অনুসন্ধান',
    noData: 'কোন তথ্য নেই',
    networkOffline: 'আপনি অফলাইনে আছেন',
    offlineMode: 'অফলাইন মোডে চলছে',
  },
  auth: {
    createPin: 'সুরক্ষা পিন তৈরি করুন',
    createPinDescription: 'আপনার আর্থিক তথ্য সুরক্ষিত রাখতে ৪-৬ অঙ্কের একটি পিন চয়ন করুন',
    enterPin: 'পিন প্রবেশ করান',
    enterPinDescription: 'অ্যাপ অ্যাক্সেস করতে আপনার সুরক্ষা পিন প্রবেশ করান',
    confirmPin: 'পিন নিশ্চিত করুন',
    pinRequired: 'পিন প্রয়োজন',
    pinLengthError: 'পিন ৪-৬ অঙ্কের হতে হবে',
    pinMatchError: 'পিন মেলেনি',
    pinOnlyDigits: 'পিনে শুধুমাত্র সংখ্যা থাকতে হবে',
    invalidPin: 'ভুল পিন',
    pinChangeSuccess: 'পিন সফলভাবে পরিবর্তন হয়েছে',
    pinCreateSuccess: 'পিন সফলভাবে তৈরি হয়েছে',
    pinSetupFailed: 'পিন তৈরি করতে ব্যর্থ। অনুগ্রহ করে আবার চেষ্টা করুন।',
    unlock: 'আনলক',
    biometricLogin: 'ফিঙ্গারপ্রিন্ট / ফেস আইডি ব্যবহার করুন',
    enableBiometrics: 'বায়োমেট্রিক সক্রিয় করুন',
    enableBiometricsDescription: 'আনলক করতে ফিঙ্গারপ্রিন্ট বা ফেস আইডি ব্যবহার করুন',
    biometricNotAvailable: 'এই ডিভাইসে বায়োমেট্রিক উপলব্ধ নয়',
    biometricNotEnrolled: 'কোন বায়োমেট্রিক তথ্য নথিভুক্ত নেই',
    biometricAuthFailed: 'বায়োমেট্রিক প্রমাণীকরণ ব্যর্থ হয়েছে',
    usePinInstead: 'পরিবর্তে পিন ব্যবহার করুন',
    lockNow: 'এখনই লক করুন',
    logout: 'লগআউট (সব রিসেট)',
    logoutConfirm: 'এটি আপনার পিন এবং সুরক্ষা সেটিংস মুছে ফেলবে। অ্যাপ অ্যাক্সেস করতে আপনাকে একটি নতুন পিন সেটআপ করতে হবে।',
    logoutFailed: 'লগআউট ব্যর্থ হয়েছে',
    attemptsRemaining: '{{count}} বার চেষ্টা বাকি',
    tooManyAttempts: 'অনেক বেশি ব্যর্থ প্রচেষ্টা। অনুগ্রহ করে পরে আবার চেষ্টা করুন।',
    changePin: 'পিন পরিবর্তন করুন',
    changePinDescription: 'আপনার বর্তমান এবং নতুন পিন প্রবেশ করান',
    currentPin: 'বর্তমান পিন',
    newPin: 'নতুন পিন',
    pinChanged: 'পিন সফলভাবে পরিবর্তিত হয়েছে',
    pinChangeFailed: 'পিন পরিবর্তন করতে ব্যর্থ',
  },
  transaction: {
    title: 'লেনদেন',
    add: 'লেনদেন যোগ করুন',
    edit: 'লেনদেন সম্পাদনা',
    save: 'লেনদেন সংরক্ষণ',
    update: 'লেনদেন আপডেট',
    delete: 'লেনদেন মুছুন',
    deleteConfirm: 'আপনি কি এই লেনদেন মুছতে চান?',
    saved: 'লেনদেন সফলভাবে সংরক্ষিত হয়েছে!',
    updated: 'লেনদেন সফলভাবে আপডেট হয়েছে!',
    deleted: 'লেনদেন সফলভাবে মুছে ফেলা হয়েছে!',
    saveFailed: 'লেনদেন সংরক্ষণ করতে ব্যর্থ। অনুগ্রহ করে আবার চেষ্টা করুন।',
    updateFailed: 'লেনদেন আপডেট করতে ব্যর্থ। অনুগ্রহ করে আবার চেষ্টা করুন।',
    deleteFailed: 'লেনদেন মুছতে ব্যর্থ',
    amount: 'পরিমাণ',
    description: 'বিবরণ',
    descriptionPlaceholder: 'এটি কীসের জন্য ছিল?',
    date: 'তারিখ',
    time: 'সময়',
    notes: 'নোট',
    notesPlaceholder: 'নোট যোগ করুন...',
    wallet: 'ওয়ালেট',
    category: 'বিভাগ',
    type: 'ধরন',
    income: 'আয়',
    expense: 'ব্যয়',
    recurring: 'পুনরাবৃত্ত লেনদেন',
    noTransactions: 'কোন লেনদেন নেই',
    noTransactionsDescription: 'আপনার প্রথম আয় বা ব্যয় যোগ করে আপনার অর্থ ট্র্যাক করা শুরু করুন',
    addFirst: 'প্রথম লেনদেন যোগ করুন',
    create: 'লেনদেন তৈরি করুন',
    selectCategory: 'অনুগ্রহ করে একটি বিভাগ নির্বাচন করুন',
    selectWallet: 'অনুগ্রহ করে একটি ওয়ালেট নির্বাচন করুন',
    invalidAmount: 'অবৈধ পরিমাণ',
    recent: 'সাম্প্রতিক লেনদেন',
    total: 'মোট {{count}}টি',
    notFound: 'লেনদেন পাওয়া যায়নি',
    detail: 'লেনদেনের বিবরণ',
    undoDelete: 'মুছে ফেলা বাতিল',
    deletedToast: 'লেনদেন মুছে ফেলা হয়েছে',
  },
  dashboard: {
    title: 'ড্যাশবোর্ড',
    totalBalance: 'মোট ব্যালেন্স',
    income: 'আয়',
    expenses: 'ব্যয়',
    netWorth: 'নেট ওয়ার্থ',
    savingsRate: 'সঞ্চয়ের হার',
    health: 'স্বাস্থ্য',
    budgetOverview: 'বাজেট ওভারভিউ',
    noTransactions: 'কোন লেনদেন নেই',
    noTransactionsDescription: 'আপনার প্রথম আয় বা ব্যয় যোগ করে আপনার অর্থ ট্র্যাক করা শুরু করুন',
    addFirst: 'প্রথম লেনদেন যোগ করুন',
    tapToSwitch: 'সুইচ করতে ট্যাপ করুন',
    noTransactionsCard: 'এখনো কোন লেনদেন নেই। আপনার খরচ ট্র্যাক করা শুরু করুন!',
  },
  budget: {
    title: 'বাজেট',
    create: 'বাজেট তৈরি করুন',
    edit: 'বাজেট সম্পাদনা',
    delete: 'বাজেট মুছুন',
    deleteConfirm: 'আপনি কি এই বাজেট মুছতে চান?',
    amount: 'বাজেটের পরিমাণ',
    period: 'সময়কাল',
    weekly: 'সাপ্তাহিক',
    monthly: 'মাসিক',
    yearly: 'বার্ষিক',
    category: 'বিভাগ',
    spent: 'ব্যয় হয়েছে',
    of: 'এর',
    remaining: 'অবশিষ্ট',
    noBudgets: 'কোন বাজেট নেই',
    noBudgetsDescription: 'আপনার খরচ ট্র্যাক করতে বাজেট তৈরি করুন',
    createFirst: 'বাজেট তৈরি করুন',
    overview: 'মাসিক বাজেট ওভারভিউ',
    budget: 'বাজেট',
    selectCategory: 'অনুগ্রহ করে একটি বিভাগ নির্বাচন করুন এবং একটি বৈধ পরিমাণ লিখুন',
    createFailed: 'বাজেট তৈরি করতে ব্যর্থ',
    deleteFailed: 'বাজেট মুছতে ব্যর্থ',
    overBudget: 'বাজেট ছাড়িয়ে গেছে!',
    categoryRequired: 'বিভাগ প্রয়োজন',
    amountRequired: 'পরিমাণ ০-এর বেশি হতে হবে',
  },
  savings: {
    title: 'সঞ্চয় লক্ষ্য',
    create: 'সঞ্চয় লক্ষ্য তৈরি করুন',
    edit: 'লক্ষ্য সম্পাদনা',
    delete: 'লক্ষ্য মুছুন',
    deleteConfirm: 'আপনি কি "{{name}}" মুছতে চান?',
    name: 'লক্ষ্যের নাম',
    namePlaceholder: 'যেমন: জরুরি তহবিল',
    targetAmount: 'লক্ষ্যের পরিমাণ',
    deadline: 'শেষ তারিখ (YYYY-MM-DD)',
    deadlinePlaceholder: '২০২৫-১২-৩১',
    currentAmount: 'বর্তমান পরিমাণ',
    contribute: 'অবদান',
    contributed: '{{name}}-এ {{amount}} অবদান যুক্ত হয়েছে',
    due: 'শেষ তারিখ {{date}}',
    of: 'এর',
    noGoals: 'কোন সঞ্চয় লক্ষ্য নেই',
    noGoalsDescription: 'আর্থিক লক্ষ্য নির্ধারণ করুন এবং সেগুলির দিকে আপনার অগ্রগতি ট্র্যাক করুন',
    createFirst: 'লক্ষ্য তৈরি করুন',
    createFailed: 'সঞ্চয় লক্ষ্য তৈরি করতে ব্যর্থ',
    deleteFailed: 'লক্ষ্য মুছতে ব্যর্থ',
    contributeFailed: 'অবদান যোগ করতে ব্যর্থ',
    allFieldsRequired: 'অনুগ্রহ করে সকল ক্ষেত্র বৈধ মান দিয়ে পূরণ করুন',
    completed: 'লক্ষ্য অর্জিত হয়েছে!',
    progress: 'অগ্রগতি',
  },
  analytics: {
    title: 'বিশ্লেষণ',
    income: 'আয়',
    expenses: 'ব্যয়',
    netIncome: 'নিট আয়',
    incomeVsExpenses: 'আয় বনাম ব্যয় (৬ মাস)',
    spendingByCategory: 'বিভাগ অনুযায়ী ব্যয়',
    ofExpenses: 'ব্যয়ের',
    noData: 'কোন আর্থিক তথ্য নেই',
    noDataDescription: 'খরচের ধরণ, প্রবণতা এবং অন্তর্দৃষ্টি দেখতে লেনদেন যোগ করুন',
    addSampleData: 'নমুনা ডেটা যোগ করুন',
    addFirstTransaction: 'প্রথম লেনদেন যোগ করুন',
  },
  reports: {
    title: 'প্রতিবেদন',
    description: 'আর্থিক প্রতিবেদন এবং সারাংশ তৈরি করুন',
    monthlySummary: 'মাসিক সারাংশ',
    monthlySummaryDesc: 'চলতি মাসের আয়, ব্যয় এবং নিট',
    categoryReport: 'বিভাগ প্রতিবেদন',
    categoryReportDesc: 'বিভাগ অনুযায়ী ব্যয় বিভাজন',
    exportCSV: 'CSV এক্সপোর্ট',
    exportCSVDesc: 'সব লেনদেন CSV হিসেবে ডাউনলোড করুন',
    annualSummary: 'বার্ষিক সারাংশ',
    annualSummaryDesc: 'এখন পর্যন্ত বছরের আর্থিক ওভারভিউ',
    generated: 'প্রতিবেদন তৈরি হয়েছে',
    csvGenerated: 'CSV তৈরি হয়েছে',
    csvExported: '{{count}}টি লেনদেন এক্সপোর্ট করা হয়েছে',
    generateFailed: 'প্রতিবেদন তৈরি করতে ব্যর্থ',
    period: 'সময়কাল',
  },
  settings: {
    title: 'সেটিংস',
    security: 'নিরাপত্তা',
    finance: 'আর্থিক',
    appearance: 'চেহারা',
    data: 'তথ্য',
    storage: 'স্টোরেজ',
    about: 'সম্পর্কে',
    changePin: 'পিন পরিবর্তন করুন',
    biometricLogin: 'বায়োমেট্রিক লগইন',
    lockNow: 'এখনই লক করুন',
    logout: 'লগআউট (সব রিসেট)',
    wallets: 'ওয়ালেট',
    savingsGoals: 'সঞ্চয় লক্ষ্য',
    debtTracker: 'ঋণ ট্র্যাকার',
    recurringTransactions: 'পুনরাবৃত্ত লেনদেন',
    reports: 'প্রতিবেদন',
    lightMode: 'লাইট মোডে স্যুইচ করুন',
    darkMode: 'ডার্ক মোডে স্যুইচ করুন',
    useSystemTheme: 'সিস্টেম থিম ব্যবহার করুন',
    backupData: 'ব্যাকআপ',
    restoreData: 'পুনরুদ্ধার',
    exportData: 'এক্সপোর্ট',
    databaseSize: 'ডাটাবেস সাইজ',
    lastBackup: 'শেষ ব্যাকআপ',
    never: 'কখনো নয়',
    unknown: 'অজানা',
    calculating: 'গণনা করা হচ্ছে...',
    backupComplete: 'ব্যাকআপ সম্পন্ন',
    backupCompleteMsg: '{{count}}টি লেনদেন ব্যাকআপ করা হয়েছে',
    backupFailed: 'ব্যাকআপ ব্যর্থ',
    restoreConfirm: 'এটি আপনার সমস্ত বর্তমান ডেটা ব্যাকআপ দিয়ে প্রতিস্থাপন করবে। আপনি কি নিশ্চিত?',
    restoreComplete: 'পুনরুদ্ধার সম্পন্ন',
    restoreFound: '{{date}} থেকে ব্যাকআপ পাওয়া গেছে',
    restoreNoBackup: 'কোন ব্যাকআপ নেই',
    restoreNoBackupMsg: 'কোন ব্যাকআপ ফাইল পাওয়া যায়নি',
    restoreFailed: 'পুনরুদ্ধার ব্যর্থ',
    exportFailed: 'এক্সপোর্ট ব্যর্থ',
    aboutText: 'আপনার গোপনীয়তা-প্রথম, অফলাইন ব্যক্তিগত অর্থ ট্র্যাকার',
    version: 'অফলাইন ফাইন্যান্স ম্যানেজার v1.0.0',
    changePinPlaceholder: 'এই বৈশিষ্ট্যটির জন্য পিন পরিবর্তন স্ক্রিন প্রয়োজন। আপাতত অ্যাপ সেটিংস ব্যবহার করুন।',
  },
  wallet: {
    title: 'ওয়ালেট',
    create: 'ওয়ালেট তৈরি করুন',
    archive: 'ওয়ালেট আর্কাইভ',
    archiveConfirm: 'আপনি কি "{{name}}" আর্কাইভ করতে চান?',
    noWallets: 'কোন ওয়ালেট নেই',
    noWalletsDescription: 'আপনার অর্থ ট্র্যাক করা শুরু করতে আপনার প্রথম ওয়ালেট তৈরি করুন',
    createFirst: 'ওয়ালেট তৈরি করুন',
    createFailed: 'ওয়ালেট তৈরি করতে ব্যর্থ',
    totalBalance: 'মোট ব্যালেন্স',
    mainWallet: 'মেইন ওয়ালেট',
  },
  debt: {
    title: 'ঋণ',
    add: 'ঋণ যোগ করুন',
    delete: 'ঋণ মুছুন',
    deleteConfirm: 'আপনি কি "{{name}}" মুছতে চান?',
    name: 'ঋণের নাম',
    namePlaceholder: 'যেমন: স্টুডেন্ট লোন',
    totalAmount: 'মোট পরিমাণ',
    interestRate: 'সুদের হার (%)',
    minimumPayment: 'ন্যূনতম পেমেন্ট',
    dueDate: 'শেষ তারিখ (YYYY-MM-DD)',
    lender: 'ঋণদাতা',
    lenderPlaceholder: 'ব্যাংকের নাম',
    remaining: 'অবশিষ্ট',
    totalOwed: 'মোট ঋণ',
    paid: 'পরিশোধিত',
    due: 'শেষ তারিখ {{date}}',
    minPayment: 'ন্যূনতম: {{amount}}/মাস',
    noDebts: 'কোন ঋণ ট্র্যাক করা নেই',
    noDebtsDescription: 'পেমেন্ট এবং সুদ ট্র্যাক করতে আপনার লোন এবং ঋণ যোগ করুন',
    addFirst: 'ঋণ যোগ করুন',
    createFailed: 'ঋণ তৈরি করতে ব্যর্থ',
    deleteFailed: 'ঋণ মুছতে ব্যর্থ',
    makePayment: 'পেমেন্ট করুন',
    paymentFailed: 'পেমেন্ট প্রক্রিয়া করতে ব্যর্থ',
    allFieldsRequired: 'অনুগ্রহ করে প্রয়োজনীয় ক্ষেত্রগুলি পূরণ করুন',
  },
  recurring: {
    title: 'পুনরাবৃত্ত',
    add: 'পুনরাবৃত্ত যোগ করুন',
    delete: 'পুনরাবৃত্ত মুছুন',
    deleteConfirm: '"{{name}}" মুছবেন?',
    description: 'বিবরণ',
    descriptionPlaceholder: 'এটি কীসের জন্য?',
    amount: 'পরিমাণ',
    category: 'বিভাগ',
    wallet: 'ওয়ালেট',
    frequency: 'ফ্রিকোয়েন্সি',
    daily: 'দৈনিক',
    weekly: 'সাপ্তাহিক',
    monthly: 'মাসিক',
    yearly: 'বার্ষিক',
    nextDate: 'পরবর্তী তারিখ (YYYY-MM-DD)',
    nextDatePlaceholder: '২০২৫-০১-০১',
    next: 'পরবর্তী: {{date}}',
    until: 'যতক্ষণ {{date}}',
    noRecurring: 'কোন পুনরাবৃত্ত লেনদেন নেই',
    noRecurringDescription: 'স্বয়ংক্রিয় ট্র্যাকিংয়ের জন্য পুনরাবৃত্ত বিল এবং আয় সেটআপ করুন',
    addFirst: 'পুনরাবৃত্ত যোগ করুন',
    save: 'পুনরাবৃত্ত সংরক্ষণ',
    createFailed: 'পুনরাবৃত্ত লেনদেন তৈরি করতে ব্যর্থ',
    deleteFailed: 'মুছতে ব্যর্থ',
    allFieldsRequired: 'অনুগ্রহ করে প্রয়োজনীয় ক্ষেত্রগুলি পূরণ করুন',
    income: 'আয়',
    expense: 'ব্যয়',
  },
  common: {
    yes: 'হ্যাঁ',
    no: 'না',
    save: 'সংরক্ষণ',
    cancel: 'বাতিল',
    delete: 'মুছুন',
    edit: 'সম্পাদনা',
    confirm: 'নিশ্চিত',
    error: 'ত্রুটি',
    success: 'সফল',
    loading: 'লোড হচ্ছে...',
    noData: 'কোন তথ্য নেই',
    retry: 'পুনরায় চেষ্টা করুন',
    unknown: 'অজানা',
    search: 'অনুসন্ধান',
    filter: 'ফিল্টার',
    sort: 'সাজান',
    clear: 'পরিষ্কার',
    select: 'নির্বাচন',
    submit: 'জমা দিন',
    undo: 'পূর্বাবস্থায়',
    deleted: 'মুছে ফেলা হয়েছে',
    comingSoon: 'শীঘ্রই আসছে',
    notFound: 'পাওয়া যায়নি',
    invalidDate: 'অবৈধ তারিখ',
    copied: 'ক্লিপবোর্ডে কপি করা হয়েছে',
    share: 'শেয়ার',
    export: 'এক্সপোর্ট',
    import: 'ইম্পোর্ট',
  },
};
