export const en = {
  app: {
    name: 'Offline Finance',
    loading: 'Loading...',
    error: 'An error occurred',
    retry: 'Try Again',
    success: 'Success',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    confirm: 'Confirm',
    ok: 'OK',
    done: 'Done',
    back: 'Back',
    search: 'Search',
    noData: 'No data available',
    networkOffline: 'You are offline',
    offlineMode: 'Running in offline mode',
  },
  auth: {
    createPin: 'Create Security PIN',
    createPinDescription: 'Choose a 4-6 digit PIN to protect your financial data',
    enterPin: 'Enter PIN',
    enterPinDescription: 'Enter your security PIN to access the app',
    confirmPin: 'Confirm PIN',
    pinRequired: 'PIN is required',
    pinLengthError: 'PIN must be 4-6 digits',
    pinMatchError: 'PINs do not match',
    pinOnlyDigits: 'PIN must contain only digits',
    invalidPin: 'Invalid PIN',
    pinChangeSuccess: 'PIN changed successfully',
    pinCreateSuccess: 'PIN created successfully',
    pinSetupFailed: 'Failed to create PIN. Please try again.',
    unlock: 'Unlock',
    biometricLogin: 'Use Fingerprint / Face ID',
    enableBiometrics: 'Enable Biometrics',
    enableBiometricsDescription: 'Use fingerprint or face ID to unlock',
    biometricNotAvailable: 'Biometrics not available on this device',
    biometricNotEnrolled: 'No biometric data enrolled',
    biometricAuthFailed: 'Biometric authentication failed',
    usePinInstead: 'Use PIN Instead',
    lockNow: 'Lock App Now',
    logout: 'Logout (Reset All)',
    logoutConfirm: 'This will clear your PIN and security settings. You will need to set up a new PIN to access the app.',
    logoutFailed: 'Failed to logout',
    attemptsRemaining: '{{count}} attempts remaining',
    tooManyAttempts: 'Too many failed attempts. Please try again later.',
    changePin: 'Change PIN',
    changePinDescription: 'Enter your current and new PIN',
    currentPin: 'Current PIN',
    newPin: 'New PIN',
    pinChanged: 'PIN changed successfully',
    pinChangeFailed: 'Failed to change PIN',
  },
  transaction: {
    title: 'Transactions',
    add: 'Add Transaction',
    edit: 'Edit Transaction',
    save: 'Save Transaction',
    update: 'Update Transaction',
    delete: 'Delete Transaction',
    deleteConfirm: 'Are you sure you want to delete this transaction?',
    saved: 'Transaction saved successfully!',
    updated: 'Transaction updated successfully!',
    deleted: 'Transaction deleted successfully!',
    saveFailed: 'Failed to save transaction. Please try again.',
    updateFailed: 'Failed to update transaction. Please try again.',
    deleteFailed: 'Failed to delete transaction',
    amount: 'Amount',
    description: 'Description',
    descriptionPlaceholder: 'What was this for?',
    date: 'Date',
    time: 'Time',
    notes: 'Notes',
    notesPlaceholder: 'Add notes...',
    wallet: 'Wallet',
    category: 'Category',
    type: 'Type',
    income: 'Income',
    expense: 'Expense',
    recurring: 'Recurring Transaction',
    noTransactions: 'No transactions yet',
    noTransactionsDescription: 'Start tracking your finances by adding your first income or expense',
    addFirst: 'Add First Transaction',
    create: 'Create Transaction',
    selectCategory: 'Please select a category',
    selectWallet: 'Please select a wallet',
    invalidAmount: 'Invalid amount',
    recent: 'Recent Transactions',
    total: '{{count}} total',
    notFound: 'Transaction not found',
    detail: 'Transaction Details',
    undoDelete: 'Undo Delete',
    deletedToast: 'Transaction deleted',
  },
  dashboard: {
    title: 'Dashboard',
    totalBalance: 'Total Balance',
    income: 'Income',
    expenses: 'Expenses',
    netWorth: 'Net Worth',
    savingsRate: 'Savings Rate',
    health: 'Health',
    budgetOverview: 'Budget Overview',
    noTransactions: 'No transactions yet',
    noTransactionsDescription: 'Start tracking your finances by adding your first income or expense',
    addFirst: 'Add First Transaction',
    tapToSwitch: 'Tap to switch',
    noTransactionsCard: 'No transactions yet. Start tracking your spending!',
  },
  budget: {
    title: 'Budgets',
    create: 'Create Budget',
    edit: 'Edit Budget',
    delete: 'Delete Budget',
    deleteConfirm: 'Are you sure you want to delete this budget?',
    amount: 'Budget Amount',
    period: 'Period',
    weekly: 'Weekly',
    monthly: 'Monthly',
    yearly: 'Yearly',
    category: 'Category',
    spent: 'spent',
    of: 'of',
    remaining: 'Remaining',
    noBudgets: 'No budgets',
    noBudgetsDescription: 'Create budgets to track your spending and stay on track',
    createFirst: 'Create Budget',
    overview: 'Monthly Budget Overview',
    budget: 'Budget',
    selectCategory: 'Please select a category and enter a valid amount',
    createFailed: 'Failed to create budget',
    deleteFailed: 'Failed to delete budget',
    overBudget: 'Over budget!',
    categoryRequired: 'Category is required',
    amountRequired: 'Amount must be greater than 0',
  },
  savings: {
    title: 'Savings Goals',
    create: 'Create Savings Goal',
    edit: 'Edit Goal',
    delete: 'Delete Goal',
    deleteConfirm: 'Are you sure you want to delete "{{name}}"?',
    name: 'Goal Name',
    namePlaceholder: 'e.g., Emergency Fund',
    targetAmount: 'Target Amount',
    deadline: 'Deadline (YYYY-MM-DD)',
    deadlinePlaceholder: '2025-12-31',
    currentAmount: 'Current Amount',
    contribute: 'Contribute',
    contributed: 'Contributed {{amount}} to {{name}}',
    due: 'Due {{date}}',
    of: 'of',
    noGoals: 'No savings goals',
    noGoalsDescription: 'Set financial goals and track your progress towards them',
    createFirst: 'Create Goal',
    createFailed: 'Failed to create savings goal',
    deleteFailed: 'Failed to delete goal',
    contributeFailed: 'Failed to add contribution',
    allFieldsRequired: 'Please fill in all fields with valid values',
    completed: 'Goal completed!',
    progress: 'Progress',
  },
  analytics: {
    title: 'Analytics',
    income: 'Income',
    expenses: 'Expenses',
    netIncome: 'Net Income',
    incomeVsExpenses: 'Income vs Expenses (6 months)',
    spendingByCategory: 'Spending by Category',
    ofExpenses: 'of expenses',
    noData: 'No financial data',
    noDataDescription: 'Add transactions to see spending patterns, trends, and insights',
    addSampleData: 'Add Sample Data',
    addFirstTransaction: 'Add First Transaction',
  },
  reports: {
    title: 'Reports',
    description: 'Generate financial reports and summaries',
    monthlySummary: 'Monthly Summary',
    monthlySummaryDesc: 'Income, expenses, and net for current month',
    categoryReport: 'Category Report',
    categoryReportDesc: 'Spending breakdown by category',
    exportCSV: 'Export CSV',
    exportCSVDesc: 'Download all transactions as CSV',
    annualSummary: 'Annual Summary',
    annualSummaryDesc: 'Year-to-date financial overview',
    generated: 'Report generated',
    csvGenerated: 'CSV Generated',
    csvExported: '{{count}} transactions exported',
    generateFailed: 'Failed to generate report',
    period: 'Period',
  },
  settings: {
    title: 'Settings',
    security: 'SECURITY',
    finance: 'FINANCE',
    appearance: 'APPEARANCE',
    data: 'DATA',
    storage: 'STORAGE',
    about: 'ABOUT',
    changePin: 'Change PIN',
    biometricLogin: 'Biometric Login',
    lockNow: 'Lock App Now',
    logout: 'Logout (Reset All)',
    wallets: 'Wallets',
    savingsGoals: 'Savings Goals',
    debtTracker: 'Debt Tracker',
    recurringTransactions: 'Recurring Transactions',
    reports: 'Reports',
    lightMode: 'Switch to Light Mode',
    darkMode: 'Switch to Dark Mode',
    useSystemTheme: 'Use System Theme',
    backupData: 'Backup Data',
    restoreData: 'Restore Data',
    exportData: 'Export Data',
    databaseSize: 'Database Size',
    lastBackup: 'Last Backup',
    never: 'Never',
    unknown: 'Unknown',
    calculating: 'Calculating...',
    backupComplete: 'Backup Complete',
    backupCompleteMsg: 'Backed up {{count}} transactions',
    backupFailed: 'Backup Failed',
    restoreConfirm: 'This will replace all current data with the backup. Are you sure?',
    restoreComplete: 'Restore Complete',
    restoreFound: 'Found backup from {{date}}',
    restoreNoBackup: 'No Backup',
    restoreNoBackupMsg: 'No backup file found',
    restoreFailed: 'Restore Failed',
    exportFailed: 'Export Failed',
    aboutText: 'Your privacy-first, offline personal finance tracker',
    version: 'Offline Finance Manager v1.0.0',
    changePinPlaceholder: 'This feature requires the PIN change screen. Use app settings for now.',
  },
  wallet: {
    title: 'Wallets',
    create: 'Create Wallet',
    archive: 'Archive Wallet',
    archiveConfirm: 'Are you sure you want to archive "{{name}}"?',
    noWallets: 'No Wallets',
    noWalletsDescription: 'Create your first wallet to start tracking your finances',
    createFirst: 'Create Wallet',
    createFailed: 'Failed to create wallet',
    totalBalance: 'Total Balance',
    mainWallet: 'Main Wallet',
  },
  debt: {
    title: 'Debts',
    add: 'Add Debt',
    delete: 'Delete Debt',
    deleteConfirm: 'Are you sure you want to delete "{{name}}"?',
    name: 'Debt Name',
    namePlaceholder: 'e.g., Student Loan',
    totalAmount: 'Total Amount',
    interestRate: 'Interest Rate (%)',
    minimumPayment: 'Minimum Payment',
    dueDate: 'Due Date (YYYY-MM-DD)',
    lender: 'Lender',
    lenderPlaceholder: 'Bank name',
    remaining: 'Remaining',
    totalOwed: 'Total Owed',
    paid: 'Paid',
    due: 'Due {{date}}',
    minPayment: 'Min: {{amount}}/mo',
    noDebts: 'No debts tracked',
    noDebtsDescription: 'Add your loans and debts to track payments and interest',
    addFirst: 'Add Debt',
    createFailed: 'Failed to create debt',
    deleteFailed: 'Failed to delete debt',
    makePayment: 'Make Payment',
    paymentFailed: 'Failed to process payment',
    allFieldsRequired: 'Please fill in required fields',
  },
  recurring: {
    title: 'Recurring',
    add: 'Add Recurring',
    delete: 'Delete Recurring',
    deleteConfirm: 'Delete "{{name}}"?',
    description: 'Description',
    descriptionPlaceholder: 'What is this for?',
    amount: 'Amount',
    category: 'Category',
    wallet: 'Wallet',
    frequency: 'Frequency',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    yearly: 'Yearly',
    nextDate: 'Next Date (YYYY-MM-DD)',
    nextDatePlaceholder: '2025-01-01',
    next: 'Next: {{date}}',
    until: 'Until {{date}}',
    noRecurring: 'No recurring transactions',
    noRecurringDescription: 'Set up recurring bills and income for automatic tracking',
    addFirst: 'Add Recurring',
    save: 'Save Recurring',
    createFailed: 'Failed to create recurring transaction',
    deleteFailed: 'Failed to delete',
    allFieldsRequired: 'Please fill in all required fields',
    income: 'Income',
    expense: 'Expense',
  },
  common: {
    yes: 'Yes',
    no: 'No',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    confirm: 'Confirm',
    error: 'Error',
    success: 'Success',
    loading: 'Loading...',
    noData: 'No data',
    retry: 'Retry',
    unknown: 'Unknown',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    clear: 'Clear',
    select: 'Select',
    submit: 'Submit',
    undo: 'Undo',
    deleted: 'Deleted',
    comingSoon: 'Coming soon',
    notFound: 'Not found',
    invalidDate: 'Invalid date',
    copied: 'Copied to clipboard',
    share: 'Share',
    export: 'Export',
    import: 'Import',
  },
};
